openapi: 3.0.3
info:
  title: Test task for T1 consulting
  version: 1.0.0
paths:
  /test:
    post:
      summary: Finds chars frequency in string
      description: ''
      operationId: findCharsFrequency
      requestBody:
        description:  String for finding
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputString'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "a: 5, c: 4, b: 1"
                description: comma-separated key-value-pairs (char:amount), if amount are the same for different chars, then they are sorted in alphabet order
        '400':
          description: Invalid input
components:
  schemas:
    InputString:
      description: DTO for input string
      type: object
      required:
        - inputString
      properties:
        inputString:
          type: string
          nullable: false
          minLength: 1
          maxLength: 100
          pattern: '^[a-z]+'
          example: "aaaaabcccc"